name: online_shop
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
    

  cupertino_icons: ^1.0.8
  getx_go: ^1.0.0
  smooth_page_indicator: ^1.1.0
  iconsax_flutter: ^1.0.0
  country_picker: ^2.0.21
  carousel_slider: ^5.1.1
  lottie: ^3.0.0
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1
  shimmer: ^2.0.0
  shared_preferences: ^2.2.2
  get: ^4.6.5
  get_storage: ^2.1.1
  intl: ^0.20.2
  http: ^1.1.0
  logger: ^2.0.1
  url_launcher: ^6.1.12
  supabase_flutter: ^2.0.0
  cached_network_image: ^3.3.1
  collection: ^1.19.1
  uuid: ^4.5.1
  payhere_mobilesdk_flutter: ^3.2.0
  pdf: ^3.10.7
  printing: ^5.12.0
  mobile_scanner: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0





flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/animations/
    - assets/data.json
    - assets/cat.json
    - assets/product.json
    - assets/category_items.json
    - assets/brand_items.json
    - assets/product_details.json
    - assets/material.json
    - assets\sources\new_arrival.json

  uses-material-design: true


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
